apiVersion: apps/v1
kind: Deployment
metadata:
  name: catweb-deployment
  labels:
    app: catweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catweb
  template:
    metadata:
      labels:
        app: catweb
    spec:
      containers:
      - name: catweb
        image: mikegcoleman/catweb:green
        ports:
        - containerPort: 5000